# Generated by Django 5.1.6 on 2025-02-18 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retailer', models.CharField(max_length=255)),
                ('purchase_date', models.CharField(max_length=10)),
                ('purchase_time', models.CharField(max_length=8)),
                ('items', models.JSONField()),
                ('total', models.FloatField()),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
